### ISSUE TITLE
Wrong data loaded to ISY

### ISSUE THREAD

**Issue by gcjacobs** [firstone/holidays-poly#1]
I have installed Holidays-poly in a Polisy with defaults and expected to get a list of know Holidays in the ISY.  Instead, I get a list of the days of the week.  I have installed and reinstalled multiple times with the same results.  
This node server will be very useful as I use the power companies' Time of Use Rates that require knowing the holidays. 
Any guidance will be appreciated.
Gerry

**Comment by firstone** [comment]
The way this supposed to work is once you set up all holiday rules or custom days / WFH days, you would use Today or Tomorrow nodes to write ISY logic. As in, "If today is On, do xxx" or "If Tomorrow is On, do yyy". Today and Tomorrow nodes would change to On for configured holiday or to Off otherwise, Sun-Man nodes are mainly for one off manual control. Via Alexa, for example. 

If you'd rather use google calendar to configure holidays / days off, I have Google holiday server instead. That one only has Today and Tomorrow. 

If you have any questions, it's better to PM me via [https://forum.universal-devices.com](url)
